### PR TITLE
Update to use `systemd` module from Ansible 2.2.

### PR DESCRIPTION
**Pull request by UmanShahzad**
https://github.com/open-craft/ansible-playbooks [uses Ansible 2.3](https://github.com/open-craft/ansible-playbooks/blob/master/requirements.txt#L1) now, so we should be able to take advantage of the `systemd` module.

### CODE REVIEW

**Review by itsjeyd — COMMENTED** [review]
@UmanShahzad LGTM! To be (implicitly) verified as part of testing https://github.com/open-craft/ansible-secrets-accounting/pull/1.

**Comment by UmanShahzad** [comment]
@itsjeyd I also incorporated a small change to use a proper leading 0 in modes. See the `mode` section in http://docs.ansible.com/ansible/latest/template_module.html for example.

**Comment by itsjeyd** [comment]
@UmanShahzad Thanks! If that change fixed one or more specific issues (?), it would worth mentioning that in the PR description.

**Comment by UmanShahzad** [comment]
@itsjeyd I don't know if it fixed a specific issue, but I know not having it caused super weird issues with permissions when I tried running the accounting playbook with Ansible 2.4, so it would be worth doing this anyway since it's what the Ansible docs say is expected.

**Review by itsjeyd — APPROVED** [review]
@UmanShahzad :+1:

- [x] I tested this: (via https://github.com/open-craft/ansible-secrets-accounting/pull/1#pullrequestreview-86142702)
- [x] I read through the code
- [x] I checked for accessibility issues
- [x] Includes documentation

**Comment by smarnach** [comment]
@UmanShahzad Thanks for this!  There are some other places where we could update this, but it's not really urgent.

**Pull request merged**
